import styles from './CheckboxList/CheckboxList.css'


export interface Bird {
    name: string,
    selected: boolean,
    birdImg: string,
    radio: string,
    shortDiscription: string,
    discription: string,
}

let radioStyle: string = styles.formRadio;

export const birdArray: Bird[] = [
    { name: 'Ворон', selected: false, birdImg: '../../../assets/img/voron.jpg', radio: radioStyle, shortDiscription: 'Corvus corax', discription: 'Ворон – крупная птица. Длина тела достигает 70 сантиметров, размах крыльев – до полутора метров. Вороны населяют окрестности Тауэра. В Англии бытует поверье, что в день, когда черные вороны улетят от Тауэра, монархия рухнет.' },
    { name: 'Журавль', selected: false, birdImg: '../../../assets/img/juravl.jpg', radio: radioStyle, shortDiscription: 'Grus grus', discription: 'Звуки, издаваемые журавлем, похожи на звонкое «кур-лы – кур-лы». Журавли чаще всего поют дуэтом – одна птица начинает запев со слога «кур», а вторая подхватывает «лы». Если птица поёт одна, то она издает только звук «кур».' },
    { name: 'Ласточка', selected: false, birdImg: '../../../assets/img/lastocka.jpg', radio: radioStyle, shortDiscription: 'Delichon urbicum', discription: 'Для ласточек характерно негромкое щебетание. Песни ласточек не смолкают на протяжении всего лета. Исследователи различают у птиц до 6 щебечущих звуков: «вит», «ви-вит», «чивит», «чиривит» и т.п. Ласточки любят петь дуэтом.' },
    { name: 'Козодой', selected: false, birdImg: '../../../assets/img/kazodoy.jpg', radio: radioStyle, shortDiscription: 'Caprimulgus europaeus', discription: 'Козодой – неприметная птица, известная благодаря своему голосу. Песня козодоя звучит как монотонная трель похожая на тарахтение мотоцикла. Такое дребезжание слышно от заката до рассвета, его тональность, частота и громкость изменяются.' },
    { name: 'Кукушка', selected: false, birdImg: '../../../assets/img/kukushka.jpg', radio: radioStyle, shortDiscription: 'Cuculus canorus', discription: 'Кукушку назвали так из-за особенностей ее песен. Звонкое «ку-ку» не спутать ни с какой другой птицей. Кукушки не строят гнезда, их потомство выращивают другие виды пернатых, которым кукушки подбрасывают свои яйца.' },
    { name: 'Синица', selected: false, birdImg: '../../../assets/img/sinitsa.jpg', radio: radioStyle, shortDiscription: 'Parus major', discription: 'В щебетании синиц различают более 40 различных звуковых сочетаний. Поют они практически круглый год, немного затихая только зимой. Синицы настоящие санитары леса. Одна пара синиц в период гнездования оберегает от вредителей десятки деревьев.' },
    { name: 'Воробей', selected: false, birdImg: '../../../assets/img/vorobey.jpg', radio: radioStyle, shortDiscription: 'Passer domesticus', discription: 'Воробьи являются самыми известными и узнаваемыми пернатыми. Их легко узнать по пестрому оперению и задорному чириканью. Воробьи относятся к синатропному виду — они селятся поблизости к человеческому жилищу.' },
    { name: 'Грач', selected: false, birdImg: '../../../assets/img/grac.jpg', radio: radioStyle, shortDiscription: 'Corvus frugilegus', discription: 'Грачи очень умные и сообразительные птицы. С помощью клюва они создают и используют простейшие орудия. У грачей развит рефлекс на звуки трактора. Услышав «тарахтение», они летят на звук – трактор пашет землю, значит, в этом месте много корма.' },
    { name: 'Галка', selected: false, birdImg: '../../../assets/img/galka.jpg', radio: radioStyle, shortDiscription: 'Coloeus monedula', discription: 'Слово «галка» произошло из старославянского языка и переводится как «чёрный». Этим словом часто называют воронов или других черных птиц. Латинское название галки «monedula» связывают со словами монета за любовь птицы к блестящим и ярким вещам.' },
    {
        name: 'Певчий дрозд', selected: false, birdImg: '../../assets/img/pevciyDrozd.jpg', radio: radioStyle, shortDiscription: 'Turdus philomelos'
        , discription: 'Дрозд — лучший певец из отряда воробьиных. Песня состоит только из красивых звучных свистов и коротких трелей. Чаще всего её можно услышать в утреннее и вечернее время. Поют дрозды в течении всего периода гнездования.'
    },
    { name: 'Сорока', selected: false, birdImg: '../../../assets/img/soroka.jpg', radio: radioStyle, shortDiscription: 'Pica pica', discription: 'Сорока очень трудолюбивая птица. Она строит до восьми гнёзд, а потом выбирает из них самое лучшее. Вход в гнездо сорок всегда обращен на юг, чтобы в жилище было теплее. Сороки являются единственными птицами, которые узнают себя в зеркале.' },
    { name: 'Сойка', selected: false, birdImg: '../../../assets/img/soyka.jpg', radio: radioStyle, shortDiscription: 'Garrulus glandarius', discription: 'Когда сойка волнуется, хохолок на её голове взъерошивается. Птица старается создать устрашающее зрелище. Сойки умеют имитировать голоса других птиц, животных и звуки, которые создает человек. На зиму они делают большие запасы желудей и орехов.' },
    {
        name: 'Зяблик', selected: false, birdImg: '../../../assets/img/zyablic.jpg', radio: radioStyle, shortDiscription: 'Fringilla coelebs'
        , discription: 'В дикой природе насчитывается 450 видов зябликов. Зимой зяблики ведут стайный образ жизни. Иногда в их семьях можно увидеть воробьев. Запевают зяблики весной, с наступлением брачного периода. Их пение – это заливистые многоминутные рулады.'
    },
    { name: 'Клёст', selected: false, birdImg: '../../../assets/img/klest.jpg', radio: radioStyle, shortDiscription: 'Loxia curvirostra', discription: 'Клестов называют «рождественскими» птицами. В естественных условиях они дают потомство зимой – в январе. Эти птицы утепляют свои гнезда мхом и шерстью животных, потому птенцам не холодно. В поисках шишек клесты могут улетать за 3500 км от гнезда.' },
    { name: 'Горлица', selected: false, birdImg: '../../../assets/img/gorlitsa.jpg', radio: radioStyle, shortDiscription: 'Streptopelia turtur', discription: 'Горлица обитает в смешанных и широколиственных лесах, а также в городских парках и поселках. Птицы часто выбирают места жизни рядом с человеком и легко привыкают к людям. Благодаря мелодичному приятному пению горлиц часто разводят в домашних условиях.' },
    { name: 'Дятел', selected: false, birdImg: '../../../assets/img/dyatel.jpg', radio: radioStyle, shortDiscription: 'Dendrocopos major', discription: 'Дятел – заметная и шумная птица, часто живет рядом с человеком. С середины января до конца июня можно услышать «барабанную дробь» дятлов – трель от вибрации веток под быстрыми ударами клюва птицы. В хорошую погоду дробь слышна в радиусе 1,5 км.' },
    { name: 'Удод', selected: false, birdImg: '../../../assets/img/udod.jpg', radio: radioStyle, shortDiscription: 'Upupa epops', discription: 'Удоды предпочитают жить на открытых ландшафтах с отдельными деревьями или рощами. Наиболее удобными для птицы являются лесостепь и саванна. Удод может выбирать места жительства рядом с человеком: пастбища, виноградники, фруктовые сады.' },
    { name: 'Стриж', selected: false, birdImg: '../../../assets/img/strij.jpg', radio: radioStyle, shortDiscription: 'Apus apus', discription: 'Стрижа можно увидеть практически в каждом уголке планеты. Они обитают как в лесных зонах, так и на открытых местностях. Живут стрижи крупными стаями. Большие колонии этих птиц можно увидеть в городах или на прибрежных скалах.' },
    {
        name: 'Жаворонок', selected: false, birdImg: '../../../assets/img/javoronok.jpg', radio: radioStyle, shortDiscription: 'Alauda arvensis'
        , discription: 'Жаворонки — перелетные птицы. С начала сентября они отлетают на юг. Возвращаются они в начале марта, независимо от того, сошел снег или нет. По прилету жаворонков определяли наступление весны и пору, когда пора пахать землю.'
    },
    { name: 'Соловей', selected: false, birdImg: '../../../assets/img/solovey.jpg', radio: radioStyle, shortDiscription: 'Luscinia luscinia', discription: 'Соловьи поют с начала мая и до конца лета. Каждая песня соловья состоит из 12 повторяющихся элементов, которые еще называют коленами. Кроме собственных трелей, соловьи легко и хорошо перенимают пение других птиц.' },
    { name: 'Скворец', selected: false, birdImg: '../../../assets/img/skvorets.jpg', radio: radioStyle, shortDiscription: 'Sturnus vulgaris', discription: 'Скворцы - перелётные птицы. Синхронный перелет больших стай скворцов называется мурмурацией. Это красивое и завораживающее явление – множество птиц будто танцуют в воздухе, образуя замысловатые фигуры, которые уменьшаются и увеличиваются в небе.' },
    { name: 'Иволга', selected: false, birdImg: '../../../assets/img/ivolga.jpg', radio: radioStyle, shortDiscription: 'Oriolus oriolus', discription: 'Мелодичность голоса иволги сравнивают со звучанием флейты. Человеку сложно разглядеть иволгу, так как она обитает высоко на деревьях. Иволга не только очень красивая, но и полезная птица. Она уничтожает ядовитых гусениц, которых не поедают другие птицы.' },
    { name: 'Свиристель', selected: false, birdImg: '../../../assets/img/sviristel.jpg',radio: radioStyle, shortDiscription: 'Bombycilla garrulus', discription: 'У свиристели очень цепкие коготки, что помогает птице удерживаться на ветках и склевывать ягоды, которые труднее всего достать. В период ухаживаний самец предлагает самке ягоду или другое угощение. Если самка его принимает, то птицы создают пару.' },
    { name: 'Щегол', selected: false, birdImg: '../../../assets/img/shegol.jpg', radio: radioStyle, shortDiscription: 'Carduelis carduelis', discription: 'Щеглы поют красиво и мелодично. И в природе, и в неволе они щебечут почти круглый год. В пении щегла различают более 20 переливчатых трелей. Щеглы привыкают к людям, и даже могут возвратиться к хозяину после того, как их выпустили на волю' },
    {
        name: 'Орёл', selected: false, birdImg: '../../../assets/img/orel.jpg', radio: radioStyle, shortDiscription: 'Aquila nipalensis'
        , discription: 'В древние времена орел был символом солнца. Орлы часто парят над землей, при этом скорость их перемещения может достигать 240 км/ч. Иллюзия медленного движения происходит из-за высоты полета – более 700 метров'
    },
    { name: 'Коршун', selected: false, birdImg: '../../../assets/img/korshun.jpg', radio: radioStyle, shortDiscription: 'Milvus migrans', discription: 'Коршуны – крупные хищники, в высоту они достигают около полуметра, а вес взрослых особей достигает 1 кг. Крылья узкие и длинные, их размах составляет 1,5 м. Коршуны часто гнездятся большими стаями и даже образуют крупные колонии.' },
    { name: 'Лунь', selected: false, birdImg: '../../../assets/img/lun.jpg', radio: radioStyle, shortDiscription: 'Circus cyaneus', discription: 'Лунь – это небольшой сокол. Питается в основном мышевидными грызунами, основа его рациона – полёвки, хомяки, мыши. Оперение луня может быть пепельно-серым. С такой птицей связано сравнение «седой, как лунь».' },
    { name: 'Сокол', selected: false, birdImg: '../../../assets/img/sokol.jpg', radio: radioStyle, shortDiscription: 'Falco peregrinus', discription: 'Латинское название сокола Falco произошло от слова «серп» из-за серповидной формы крыльев. Длинные и широкие крылья позволяют соколу высоко подниматься в небо и свободно парить. Скорость полёта сокола достигает 280-320 километров в час.' },
    { name: 'Ястреб', selected: false, birdImg: '../../../assets/img/yastreb.jpg', radio: radioStyle, shortDiscription: 'Accipiter gentilis', discription: 'Для всех ястребов характерны широкие и короткие крылья. Ещё один отличительный признак - белые «брови» над глазами. Славянские дружинники размещали изображение ястреба на своих знаменах, как символ отваги, мощи и безжалостности к врагам.' },
    { name: 'Филин', selected: false, birdImg: '../../../assets/img/filin.jpg', radio: radioStyle, shortDiscription: 'Bubo bubo', discription: 'Полет филина бесшумный, зрение очень острое. Эти особенности делают птицу непревзойденным ночным охотником. У филина нет естественных врагов, ни один зверь не охотится на взрослых птиц. А вот на птенцов нападают лисы и волки.' },
    { name: 'Альбатрос', selected: false, birdImg: '../../../assets/img/batros.jpg', radio: radioStyle, shortDiscription: 'Diomedea exulans', discription: 'Альбатрос - самая крупная летающая птица в мире. Размах крыльев достигает три с половиной, вес - десять килограммов. Большую часть жизни альбатросы проводят в воздухе, покрывая над океанскими просторами огромные расстояния' },
    { name: 'Олуша', selected: false, birdImg: '../../../assets/img/olusha.jpg', radio: radioStyle, shortDiscription: 'Sula nebouxii', discription: 'Особенностью голубоногой олуши является не только насыщенный ярко-синий цвет лапок, но еще и тот факт, что они очень теплые. В то время как другие виды птиц греют кладки своим телом, голубоногая олуша делает это с помощью лапок' },
    { name: 'Буревестник', selected: false, birdImg: '../../../assets/img/burevestnik.jpg',radio: radioStyle, shortDiscription: 'Puffinus griseus', discription: 'Размеры буревестниковых разные. Самые маленькие из них в длину составляют до 25 см, самые большие - до 1 м, при размахе крыльев около 2 м. Существует поверье, что появление буревестника в воздухе предвещает бурю, о чем говорит само название птицы.' },
    { name: 'Пеликан', selected: false, birdImg: '../../../assets/img/pelikan.jpg', radio: radioStyle, shortDiscription: 'Pelecanus', discription: 'Пеликаны — обитатели морей и рек. Ходят они неуклюже, но хорошо летают и плавают. Питаются в основном рыбой, устраивают коллективные охоты — выстроившись полукругом хлопают по воде крыльями и клювами и вытесняют напуганную рыбу на мелководье.' },
    { name: 'Пингвин', selected: false, birdImg: '../../../assets/img/pingvin.jpg', radio: radioStyle, shortDiscription: 'Aptenodytes forsteri', discription: 'Самец императорского пингвина достигает роста 130 см, его масса может приближаться к 50 кг. Из всех современных пингвинов этот вид – самый крупный. Питание пингвина состоит из рыбы, кальмаров и криля. Охотятся птицы в океане большими группами.' },
    { name: 'Чайка', selected: false, birdImg: '../../../assets/img/chayka.jpg', radio: radioStyle, shortDiscription: 'Larus argentatus', discription: 'Чайки населяют берега морей, озёр, рек, водохранилищ, болот, часто гнездятся на островах. С конца прошлого века чайки стали появляться в крупных городах, где устраивает гнёзда на крышах зданий. Все чайки ведут колониальный образ жизни.' },
    { name: '*****', selected: false, birdImg: '../../../assets/img/default.jpg', radio: radioStyle, shortDiscription: '', discription: '' },

]; 
